### ISSUE TITLE
OIDC docs with popular providers

### ISSUE THREAD

**Issue by jamilbk** [firezone/firezone#4573]
Replicate the SSO docs from https://www.firezone.dev/docs/authenticate/oidc to https://www.firezone.dev/kb/authenticate

Maybe also add some new popular ones like Authentik, Authelia, etc.
```[tasklist]
### Tasks
- [ ] Auth0 (SaaSS) #5523
- [ ] Authelia (self-hosted only)
- [ ] Authentik (Open core + managed)
- [x] Azure AD, now "Microsoft Entra ID" (Already documented)
- [x] Google Workspace (Already documented)
- [ ] Keycloak (self-hosted only)
- [x] Okta (Already documented)
- [ ] Onelogin (SaaSS)
- [ ] Ory (Open core + managed?)
- [ ] Zitadel (Open core + SaaSS)
```

**Comment by jamilbk** [comment]
cc @ReactorScram

**Comment by ReactorScram** [comment]
For this, should I use my Firezone email to sign up accounts for those services to document them?

**Comment by jamilbk** [comment]
Ah, good question. Let me make a Group we can use for demos and screenshots and add you to it.

Yeah Vultr works. Here's a list I just put together:

- Onelogin
- Auth0
- Keycloak
- Authelia
- Ory
- Authentik
- Zitadel

The one thing about self-hosted OIDC is that we have to be able to fetch their discovery document URI, so that might be worth calling out. If there's a cloud version _and_ self-hosted version, the cloud version is probably easier to document.
